/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.manager.View;

import Control.BookingController;
import Control.RoomController;
import Model.Booking;
import Model.Room;
import java.util.Date;

/**
 *
 * @author 09046138950
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRelatorios = new javax.swing.JButton();
        buttonQuartos = new javax.swing.JButton();
        buttonCheckinCheckout = new javax.swing.JButton();
        buttonReservas = new javax.swing.JButton();
        buttonRestaurante = new javax.swing.JButton();
        buttonSpa = new javax.swing.JButton();
        buttonLavanderia = new javax.swing.JButton();
        buttonFinanceiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        buttonRelatorios.setText("Relatórios");
        buttonRelatorios.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonRelatorios.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonRelatorios.setPreferredSize(new java.awt.Dimension(150, 150));

        buttonQuartos.setText("Quartos");
        buttonQuartos.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonQuartos.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonQuartos.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuartosActionPerformed(evt);
            }
        });

        buttonCheckinCheckout.setText("Checkin / Checkout");
        buttonCheckinCheckout.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonCheckinCheckout.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonCheckinCheckout.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonCheckinCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckinCheckoutActionPerformed(evt);
            }
        });

        buttonReservas.setText("Reservas");
        buttonReservas.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonReservas.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonReservas.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservasActionPerformed(evt);
            }
        });

        buttonRestaurante.setText("Restaurante");
        buttonRestaurante.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonRestaurante.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonRestaurante.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestauranteActionPerformed(evt);
            }
        });

        buttonSpa.setText("Spa");
        buttonSpa.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonSpa.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonSpa.setPreferredSize(new java.awt.Dimension(150, 150));

        buttonLavanderia.setText("Lavanderia");
        buttonLavanderia.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonLavanderia.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonLavanderia.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonLavanderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLavanderiaActionPerformed(evt);
            }
        });

        buttonFinanceiro.setText("Financeiro");
        buttonFinanceiro.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonFinanceiro.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonFinanceiro.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinanceiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCheckinCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLavanderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCheckinCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLavanderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFinanceiroActionPerformed

    private void buttonRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestauranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRestauranteActionPerformed

    private void buttonLavanderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLavanderiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLavanderiaActionPerformed

    private void buttonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservasActionPerformed
        BookingMenu bookingMenu = new BookingMenu();
        bookingMenu.setVisible(true);
    }//GEN-LAST:event_buttonReservasActionPerformed

    private void buttonCheckinCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckinCheckoutActionPerformed
        CheckinCheckoutMenu checkinCheckoutMenu = new CheckinCheckoutMenu();
        checkinCheckoutMenu.setVisible(true);
    }//GEN-LAST:event_buttonCheckinCheckoutActionPerformed

    private void buttonQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuartosActionPerformed
        RoomMenu roomMenu = new RoomMenu();
        roomMenu.setVisible(true);
    }//GEN-LAST:event_buttonQuartosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheckinCheckout;
    private javax.swing.JButton buttonFinanceiro;
    private javax.swing.JButton buttonLavanderia;
    private javax.swing.JButton buttonQuartos;
    private javax.swing.JButton buttonRelatorios;
    private javax.swing.JButton buttonReservas;
    private javax.swing.JButton buttonRestaurante;
    private javax.swing.JButton buttonSpa;
    // End of variables declaration//GEN-END:variables
}
