/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.manager.View;

import Control.BookingController;
import Control.RoomController;
import Model.Booking;
import Model.Room;
import java.util.Date;

/**
 *
 * @author 09046138950
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRelatorios = new javax.swing.JButton();
        buttonQuartos = new javax.swing.JButton();
        buttonCheckinCheckout = new javax.swing.JButton();
        buttonReservas = new javax.swing.JButton();
        buttonFinanceiro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1200, 720));
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 720));
        getContentPane().setLayout(null);

        buttonRelatorios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonRelatorios.setText("Relatórios");
        buttonRelatorios.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonRelatorios.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonRelatorios.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRelatorios);
        buttonRelatorios.setBounds(690, 350, 150, 150);

        buttonQuartos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonQuartos.setText("Quartos");
        buttonQuartos.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonQuartos.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonQuartos.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuartosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonQuartos);
        buttonQuartos.setBounds(370, 350, 150, 150);

        buttonCheckinCheckout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCheckinCheckout.setText("Checkin-out");
        buttonCheckinCheckout.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonCheckinCheckout.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonCheckinCheckout.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonCheckinCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckinCheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCheckinCheckout);
        buttonCheckinCheckout.setBounds(530, 350, 150, 150);

        buttonReservas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonReservas.setText("Agendamentos");
        buttonReservas.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonReservas.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonReservas.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReservasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonReservas);
        buttonReservas.setBounds(210, 350, 150, 150);

        buttonFinanceiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonFinanceiro.setText("Financeiro");
        buttonFinanceiro.setMaximumSize(new java.awt.Dimension(150, 150));
        buttonFinanceiro.setMinimumSize(new java.awt.Dimension(150, 150));
        buttonFinanceiro.setPreferredSize(new java.awt.Dimension(150, 150));
        buttonFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFinanceiro);
        buttonFinanceiro.setBounds(850, 350, 150, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hotel Manager");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 100, 680, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinanceiroActionPerformed
        //criação da tela de finanças
        FinantialMenu finantialMenu = new FinantialMenu();
        finantialMenu.setVisible(true);
    }//GEN-LAST:event_buttonFinanceiroActionPerformed

    private void buttonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReservasActionPerformed
        //criação da tela de agendamentos
        BookingMenu bookingMenu = new BookingMenu();
        bookingMenu.setVisible(true);
    }//GEN-LAST:event_buttonReservasActionPerformed

    private void buttonCheckinCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckinCheckoutActionPerformed
        //criação da tela de checkin e checkout
        CheckinCheckoutMenu checkinCheckoutMenu = new CheckinCheckoutMenu();
        checkinCheckoutMenu.setVisible(true);
    }//GEN-LAST:event_buttonCheckinCheckoutActionPerformed

    private void buttonQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuartosActionPerformed
        //criação da tela de quartos
        RoomMenu roomMenu = new RoomMenu();
        roomMenu.setVisible(true);
    }//GEN-LAST:event_buttonQuartosActionPerformed

    private void buttonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatoriosActionPerformed
        //criação da tela de relatório
        ReportMenu reportMenu = new ReportMenu();
        reportMenu.setVisible(true);
    }//GEN-LAST:event_buttonRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheckinCheckout;
    private javax.swing.JButton buttonFinanceiro;
    private javax.swing.JButton buttonQuartos;
    private javax.swing.JButton buttonRelatorios;
    private javax.swing.JButton buttonReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
