/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.manager.View;

import Control.RoomController;
import Model.Room;

/**
 *
 * @author Schork
 */
public class ModalRoom extends javax.swing.JFrame {

    /**
     * Creates new form ModalRoom
     */
    Room room = new Room();

    public ModalRoom() {
        initComponents();
        this.buttonDelete.setEnabled(false);
        this.buttonEdit.setEnabled(false);
    }

    public ModalRoom(Room room) {
        initComponents();
        this.room = room;
        this.buttonSave.setEnabled(false);
        this.roomNumberTextInput.setText(String.valueOf(room.getNumber()));
        this.bedsNumberTextInput.setText(String.valueOf(room.getAmountOfBeds()));
        if (room.hasRoomService()) {
            hasRoomServiceRadioButton.setSelected(true);
        }
        if (room.hasBathroom()) {
            this.hasBathRoomRadioButton.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        roomNumberTextInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bedsNumberTextInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        guestTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        hasBathRoomRadioButton = new javax.swing.JRadioButton();
        hasRoomServiceRadioButton = new javax.swing.JRadioButton();
        buttonSave = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar quarto");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Número do quarto:");

        roomNumberTextInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomNumberTextInput.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Número de camas:");

        bedsNumberTextInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bedsNumberTextInput.setText("0");

        guestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        jScrollPane1.setViewportView(guestTable);

        hasBathRoomRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hasBathRoomRadioButton.setText("Possui banheiro");

        hasRoomServiceRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hasRoomServiceRadioButton.setText("Possui serviço de quarto");

        buttonSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonDelete.setText("Excluir");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gerenciar quarto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Hóspedes no quarto no momento");

        buttonEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonEdit.setText("Editar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasBathRoomRadioButton)
                    .addComponent(hasRoomServiceRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bedsNumberTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(roomNumberTextInput))
                .addGap(248, 248, 248))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomNumberTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bedsNumberTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasBathRoomRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasRoomServiceRadioButton)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonDelete)
                    .addComponent(buttonEdit))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //criação de quarto
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        int number = Integer.parseInt(this.roomNumberTextInput.getText());
        int beds = Integer.parseInt(this.bedsNumberTextInput.getText());
        
        //verificando integridade dos inputs se são válidos
        if (number > 0 && beds > 0) {
            boolean hasBathroom = false;
            if (this.hasBathRoomRadioButton.isSelected()) {
                hasBathroom = true;
            }
            boolean hasRoomService = false;
            if (this.hasRoomServiceRadioButton.isSelected()) {
                hasRoomService = true;
            }
            
            //criando quarto e inserindo no arquivo
            Room room = new Room(number, beds, false, false, hasBathroom, hasRoomService);

            try {
                RoomController roomController = new RoomController();
                roomController.createNewRoom(room);
                this.dispose();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed
    
    //edição de quarto
    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        RoomController roomController = new RoomController();
        
        //pegando quarto selecionado do arquivo e editando seus atributos
        Room room = roomController.findRoomByNumber(Integer.parseInt(this.roomNumberTextInput.getText()));
        room.setAmountOfBeds(Integer.parseInt(this.bedsNumberTextInput.getText()));
        room.setNumber(Integer.parseInt(this.roomNumberTextInput.getText()));
        if (this.hasBathRoomRadioButton.isSelected()) {
            room.setHasBathroom(true);
        } else {
            room.setHasBathroom(false);
        }

        if (this.hasRoomServiceRadioButton.isSelected()) {
            room.setHasRoomService(true);
        } else {
            room.setHasRoomService(false);
        }
        
        //chamando método para editar quarto no arquivo
        roomController.editRoom(room, this.room.getNumber());
        this.dispose();
    }//GEN-LAST:event_buttonEditActionPerformed
    
    //exclusão de quarto
    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        RoomController roomController = new RoomController();
        
        //chamando método para deletar quarto partindo do id selecionado
        roomController.deleteRoomFromFile(this.room.getNumber());
        this.dispose();
    }//GEN-LAST:event_buttonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bedsNumberTextInput;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JTable guestTable;
    private javax.swing.JRadioButton hasBathRoomRadioButton;
    private javax.swing.JRadioButton hasRoomServiceRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roomNumberTextInput;
    // End of variables declaration//GEN-END:variables
}
