/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.manager.View;

import Control.BookingController;
import Control.GuestController;
import Control.RoomController;
import Model.Booking;
import Model.Guest;
import Model.Room;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Schork
 */
public class ModalBooking extends javax.swing.JFrame {

    /**
     * Creates new form ModalBooking
     */
    private Booking booking = new Booking();
    
    public ModalBooking() {
        initComponents();
        this.buttonDelete.setEnabled(false);
        this.buttonEdit.setEnabled(false);
    }
    
    public ModalBooking(Booking booking) {
        initComponents();
        this.booking = booking;
        radioButtonCheckinAuto.setEnabled(false);
        this.buttonSave.setEnabled(false);
        this.costInputText.setText(String.valueOf(booking.getCost()));
        this.roomPicker.addItem(String.valueOf(booking.getRoom().getNumber()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomPicker = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        guestsTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jLabel2 = new javax.swing.JLabel();
        costInputText = new javax.swing.JTextField();
        buttonAddGuest = new javax.swing.JButton();
        radioButtonCheckinAuto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        guestPicker = new javax.swing.JComboBox<>();
        buttonRegisterGuest = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        roomPicker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Número do quarto:");

        buttonSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDelete.setText("Excluir");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        guestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Código", "Nome"
            }
        ));
        guestsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(guestsTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Custo inicial:");

        costInputText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        costInputText.setText("0");

        buttonAddGuest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAddGuest.setText("Adicionar hóspede");
        buttonAddGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddGuestActionPerformed(evt);
            }
        });

        radioButtonCheckinAuto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioButtonCheckinAuto.setText("Incluir checkin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nome do hóspede:");

        guestPicker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buttonRegisterGuest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonRegisterGuest.setText("Cadastrar nova pessoa");
        buttonRegisterGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterGuestActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Hóspedes:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agendamento");

        buttonEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonEdit.setText("Editar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRegisterGuest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(guestPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(buttonAddGuest)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(radioButtonCheckinAuto)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(roomPicker, 0, 373, Short.MAX_VALUE)
                                                .addComponent(costInputText)))))))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(costInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonCheckinAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddGuest)
                    .addComponent(guestPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonRegisterGuest)
                        .addComponent(buttonEdit)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddGuestActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) guestsTable.getModel();
        GuestController guestController = new GuestController();
        Guest guest = guestController.findGuestByName(String.valueOf(this.guestPicker.getSelectedItem()));
        
        boolean canAdd = true;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            int code = (int) tabela.getValueAt(i, 0);
            if (code == guest.getId()) {
                canAdd = false;
            }
        }
        
        if (canAdd) {
            tabela.addRow(new Object[]{
                guest.getId(), guest.getName()
            });
        }
    }//GEN-LAST:event_buttonAddGuestActionPerformed

    private void buttonRegisterGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterGuestActionPerformed
        ModalGuest modalGuest = new ModalGuest();
        modalGuest.setVisible(true);
    }//GEN-LAST:event_buttonRegisterGuestActionPerformed

    private void guestsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestsTableMouseClicked
//        Guest guest = new Guest((int) guestsTable.getValueAt(guestsTable.rowAtPoint(evt.getPoint()), 0), (String) guestsTable.getValueAt(guestsTable.rowAtPoint(evt.getPoint()), 1));;
//        ModalGuest modalGuest = new ModalGuest(guest);
//        modalGuest.setVisible(true);
    }//GEN-LAST:event_guestsTableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        reloadPickerGuests();
        reloadPickerRooms();
    }//GEN-LAST:event_formWindowActivated

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        BookingController bookingController = new BookingController();
        RoomController roomController = new RoomController();
        
        ArrayList<Booking> bookings = bookingController.getAllBookings();
        if (bookings.size() > 0) {
            Booking lastBooking = bookings.get(bookings.size() - 1);
            int newBookingCode = lastBooking.getCode() + 1;
            
            Room room = roomController.findRoomByNumber(Integer.parseInt(String.valueOf(this.roomPicker.getSelectedItem())));
            
            boolean doCheckin = false;
            if (this.radioButtonCheckinAuto.isSelected()) {
                doCheckin = true;
            }
            
            if (doCheckin) {
                Booking booking = new Booking(newBookingCode, room, false, new Date().toString(), null, Float.parseFloat(this.costInputText.getText()));
                bookingController.createNewBooking(booking);
            } else {
                Booking booking = new Booking(newBookingCode, room, false, null, null, Float.parseFloat(this.costInputText.getText()));
                bookingController.createNewBooking(booking);
            }
        } else {
            Room room = roomController.findRoomByNumber(Integer.parseInt(String.valueOf(this.roomPicker.getSelectedItem())));
            
            boolean doCheckin = false;
            if (this.radioButtonCheckinAuto.isSelected()) {
                doCheckin = true;
            }
            if (doCheckin) {
                Booking booking = new Booking(1, room, false, new Date().toString(), null, Float.parseFloat(this.costInputText.getText()));
                bookingController.createNewBooking(booking);
            } else {
                Booking booking = new Booking(1, room, false, null, null, Float.parseFloat(this.costInputText.getText()));
                bookingController.createNewBooking(booking);
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        BookingController bookingController = new BookingController();
        bookingController.deleteBookingFromFile(this.booking.getCode());
        this.dispose();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditActionPerformed
    
    private void reloadPickerRooms() {
        RoomController roomController = new RoomController();
        ArrayList<Room> rooms = roomController.getAllRooms();

        //Limpeza das linhas do picker
        roomPicker.removeAllItems();

        //Repopulando picker
        for (Room room : rooms) {
            roomPicker.addItem(String.valueOf(room.getNumber()));
        }
    }
    
    private void reloadPickerGuests() {
        GuestController guestController = new GuestController();
        ArrayList<Guest> guests = guestController.getAllGuests();

        //Limpeza das linhas do picker
        guestPicker.removeAllItems();

        //Repopulando picker
        for (Guest guest : guests) {
            guestPicker.addItem(guest.getName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddGuest;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRegisterGuest;
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField costInputText;
    private javax.swing.JComboBox<String> guestPicker;
    private javax.swing.JTable guestsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioButtonCheckinAuto;
    private javax.swing.JComboBox<String> roomPicker;
    // End of variables declaration//GEN-END:variables
}
